fix #11
fastai/execnb pull request #12
Opened 2022-07-04 10:25 UTC by seeM

This adapts IPython's [`DisplayHook.quiet`](https://github.com/ipython/ipython/blob/359181665fcc65c6ff4d76430348ca27858b0443/IPython/core/displayhook.py#L84) to silence cells with trailing `;`s.

It uses `tokenize` to ignore comments after the `;`. If we're not too worried about maintaining exact consistency, we could do something like `self.shell._code.rstrip().endswith(';')`, but I think using `tokenize` is pretty lightweight anyway.

cc @hamelsmu @jph00

2022-07-04 23:38 UTC, jph00 commented
@seeM many thanks. Just one suggested change - see above.

BTW did you look at the ipython source to see how they handle this? Do they already have some function we can just use? (I'm fine doing it with `tokenize` otherwise).

2022-07-05 22:34 UTC, seeM commented
@jph00 I can't seem to find your suggested change anywhere on GitHub or ReviewNB.

This is a copy paste of [DisplayHook.quiet](https://github.com/ipython/ipython/blob/359181665fcc65c6ff4d76430348ca27858b0443/IPython/core/displayhook.py#L84) from ipython with stylistic changes and with the reference `self.shell.history_manager.input_hist_parsed[-1]` changed to `self.shell._code`. Alternatives could be to get `history_manager` working as in ipython (not sure if worth it) or patch it so that `DisplayHook.quiet` works.

2022-07-05 22:42 UTC, jph00 requested changes
apologies there was a button i had to click to make the suggestion appear!

2022-07-05 22:43 UTC, jph00 commented
> @jph00 I can't seem to find your suggested change anywhere on GitHub or ReviewNB.

Sorry about that - you should be able to see it now.

2022-07-05 22:53 UTC, seeM commented on execnb/shell.py
> +from fastcore.test import *
Fixed in https://github.com/fastai/execnb/pull/12/commits/e2b3d9a2831d06efc22f966eaaa344ca31c087f9

2022-07-05 23:01 UTC, merged